import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#eef6ff',
    padding: 24,
    justifyContent: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#0b3d66',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#35556b',
    textAlign: 'center',
    marginBottom: 24,
  },
  button: {
    backgroundColor: '#0b75bd',
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#0b75bd',
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
  },
  secondaryButtonText: {
    color: '#0b75bd',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  progress: {
    fontSize: 15,
    color: '#35556b',
    marginBottom: 16,
    textAlign: 'center',
  },
  question: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0b3d66',
    marginBottom: 24,
    textAlign: 'center',
  },
  optionButton: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  optionText: {
    fontSize: 16,
    color: '#0b3d66',
    textAlign: 'center',
  },
  smallText: {
    fontSize: 14,
    color: '#35556b',
    textAlign: 'center',
    marginTop: 12,
  },
  resultText: {
    fontSize: 20,
    textAlign: 'center',
    color: '#0b3d66',
    marginBottom: 8,
  },
  card: {
    backgroundColor: 'white',
    padding: 18,
    borderRadius: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  cardTitle: {
    fontSize: 16,
    color: '#35556b',
  },
  cardValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0b3d66',
    marginTop: 6,
  },
  badge: {
    fontSize: 18,
    marginTop: 8,
    color: '#0b3d66',
  },
  resetButton: {
    backgroundColor: '#d9534f',
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
  },
  dashboardCard: {
    backgroundColor: 'white',
    padding: 18,
    borderRadius: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  dashboardCardTitle: {
    fontSize: 14,
    color: '#35556b',
    marginBottom: 4,
  },
  dashboardCardValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  progressBarBackground: {
    height: 12,
    backgroundColor: '#d6e8f5',
    borderRadius: 6,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: 12,
    backgroundColor: '#0b75bd',
    borderRadius: 6,
  },
  progressLabel: {
    fontSize: 13,
    color: '#35556b',
    marginTop: 6,
    textAlign: 'right',
  },
  quickAccessRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  quickAccessCard: {
    backgroundColor: 'white',
    width: '48%',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#d6e8f5',
    alignItems: 'center',
  },
  quickAccessText: {
    fontSize: 14,
    color: '#0b3d66',
    fontWeight: 'bold',
    marginTop: 6,
    textAlign: 'center',
  },
  demoLabel: {
    fontSize: 11,
    color: '#8a9ba8',
    fontStyle: 'italic',
    marginTop: 4,
  },
  sectionHeading: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0b3d66',
    marginTop: 20,
    marginBottom: 10,
  },
  resourceItem: {
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  resourceItemTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0b3d66',
    marginBottom: 4,
  },
  resourceItemDetail: {
    fontSize: 13,
    color: '#35556b',
  },
  contactRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  contactName: {
    fontSize: 14,
    color: '#0b3d66',
    fontWeight: 'bold',
  },
  contactNumber: {
    fontSize: 14,
    color: '#0b75bd',
    fontWeight: 'bold',
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  checklistCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#0b75bd',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checklistCheckboxChecked: {
    backgroundColor: '#0b75bd',
  },
  checklistTextContainer: {
    flex: 1,
  },
  alertCard: {
    backgroundColor: '#fff0f0',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f5b8b8',
  },
  alertArea: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#a83232',
    marginBottom: 4,
  },
  alertMessage: {
    fontSize: 14,
    color: '#6b3a3a',
    marginBottom: 4,
  },
  alertSeverity: {
    fontSize: 12,
    color: '#a83232',
    fontWeight: 'bold',
  },
  noAlertsCard: {
    backgroundColor: '#f0fff4',
    padding: 20,
    borderRadius: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#b8f5c8',
    alignItems: 'center',
  },
  noAlertsText: {
    fontSize: 16,
    color: '#2f7a4a',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  lastUpdatedText: {
    fontSize: 12,
    color: '#8a9ba8',
    textAlign: 'center',
    marginTop: 12,
  },
  mapContainer: {
    width: '100%',
    height: 400,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
  },
  map: {
    width: '100%',
    height: '100%',
  },
    statusBannerGreen: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#eafaf0',
    borderColor: '#b8f5c8',
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  statusBannerRed: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff0f0',
    borderColor: '#f5b8b8',
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
    statusBannerAmber: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff8e6',
    borderColor: '#f5d98b',
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  errorCard: {
    backgroundColor: '#fff8e6',
    padding: 20,
    borderRadius: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#f5d98b',
    alignItems: 'center',
  },
  demoRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  demoButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#f5b8b8',
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  demoButtonText: {
    fontSize: 13,
    color: '#b3261e',
    fontWeight: '600',
  },
  statusBannerText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  statusBannerSubtext: {
    fontSize: 13,
    color: '#5a7284',
  },
  headerRow: {
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#5a7284',
    marginTop: 2,
  },
  ringCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 14,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  ringCardTextContainer: {
    marginLeft: 18,
    flex: 1,
  },
  ringCardLabel: {
    fontSize: 13,
    color: '#5a7284',
  },
  ringCardValue: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  listRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  listRowTextContainer: {
    flex: 1,
  },
  listRowTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  listRowSubtitle: {
    fontSize: 12,
    color: '#5a7284',
    marginTop: 2,
  },
  listRowChevron: {
    fontSize: 20,
    color: '#a8bccb',
  },
    tabPillRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  tabPill: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#d6e8f5',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 24,
    marginRight: 10,
  },
  tabPillActive: {
    backgroundColor: '#0b75bd',
    borderColor: '#0b75bd',
  },
  tabPillText: {
    color: '#0b3d66',
    fontWeight: 'bold',
    fontSize: 14,
  },
  tabPillTextActive: {
    color: 'white',
  },
  checklistWidgetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  checklistWidgetText: {
    flex: 1,
    marginLeft: 14,
  },
  checklistWidgetTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  checklistWidgetSubtitle: {
    fontSize: 13,
    color: '#5a7284',
    marginTop: 2,
  },
  resumeButton: {
    backgroundColor: '#0b75bd',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
  },
  resumeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 13,
  },
  guideCountLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#8a9ba8',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  resourceItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  resourceItemTime: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0b75bd',
  },
    regionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d6e8f5',
  },
  regionRowRaining: {
    backgroundColor: '#eaf3fb',
    borderColor: '#a8cbe8',
  },
  regionName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  regionSubtext: {
    fontSize: 12,
    color: '#5a7284',
    marginTop: 2,
  },
  regionStatusText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
    mapIconBubbleSun: {
    backgroundColor: 'white',
    borderRadius: 14,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e8d98a',
  },
  mapIconBubbleRain: {
    backgroundColor: 'white',
    borderRadius: 14,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7fb3e0',
  },
  mapIconEmoji: {
    fontSize: 14,
  },
    categoryCard: {
    backgroundColor: 'white',
    borderRadius: 14,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#d6e8f5',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0b3d66',
  },
  categoryCardSubtitle: {
    fontSize: 12,
    color: '#5a7284',
    marginTop: 2,
  },
});
